# PRACTICA 8 - REGRESION LINEAL MULTIPLE Y LOGISTICA

## Andres Cabero Mata

In [1]:
import pandas as pd

### 1 - Conjunto de datos Avila

In [2]:
#Comandos bash para la creación del fichero csv (una vez descargados los datos)
#echo "F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, Class" > avila.csv
#cat avila-tr.txt >> avila.csv
#cat avila-ts.txt >> avila.csv

In [3]:
avila = pd.read_csv("avila.csv")

In [4]:
avila

F1        F2        F3        F4        F5        F6        F7  \
0      0.266074 -0.165620  0.320980  0.483299  0.172340  0.273364  0.371178   
1      0.130292  0.870736 -3.210528  0.062493  0.261718  1.436060  1.465940   
2     -0.116585  0.069915  0.068476 -0.783147  0.261718  0.439463 -0.081827   
3      0.031541  0.297600 -3.210528 -0.583590 -0.721442 -0.307984  0.710932   
4      0.229043  0.807926 -0.052442  0.082634  0.261718  0.148790  0.635431   
...         ...       ...       ...       ...       ...       ...       ...   
20862 -0.128929 -0.040001  0.057807  0.557894  0.261718 -0.930856 -0.044076   
20863  0.266074  0.556689 -0.020434  0.176624  0.261718 -0.515608  0.597681   
20864 -0.054866  0.580242  0.032912 -0.016668  0.261718  1.519109  0.371178   
20865  0.080916  0.588093  0.015130  0.002250  0.261718 -0.930856 -0.270579   
20866  0.377169  0.014957  0.381439  0.292753  0.261718 -1.470679 -0.006326   

             F8        F9       F10  Class  
0      0.929823  0.251173  0.159345      A  
1      0.636203  0.282354  0.515587      A  
2     -0.888236 -0.123005  0.582939      A  
3      1.051693  0.594169 -0.533994      A  
4      0.051062  0.032902 -0.086652      F  
...         ...       ...       ...    ...  
20862  1.158458  2.277968 -0.699884      X  
20863  0.178349  0.625350 -0.657245      G  
20864 -0.985508 -0.403638  1.276301      A  
20865  0.163807 -0.091823 -0.593329      F  
20866 -0.494919 -0.247731 -1.212974      H  

[20867 rows x 11 columns]

### 2 - Regresion lineal multiple

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [6]:
data = np.asarray(avila)[:,:-1]
target = np.asarray(avila)[:,-1]

In [7]:
#Estándarización de los datos
scaler = StandardScaler()
x = scaler.fit_transform(data)

In [8]:
x

array([[ 2.66078450e-01, -6.45338065e-02,  3.01131959e-01, ...,
         9.29814214e-01,  2.38262784e-01,  1.59277859e-01],
       [ 1.30294181e-01,  2.98711346e-01, -3.03621667e+00, ...,
         6.36188094e-01,  2.68091434e-01,  5.15524876e-01],
       [-1.16586945e-01,  1.80217508e-02,  6.25104183e-02, ...,
        -8.88282682e-01, -1.19686747e-01,  5.82877824e-01],
       ...,
       [-5.48669136e-02,  1.96892534e-01,  2.89016974e-02, ...,
        -9.85556710e-01, -3.88148417e-01,  1.27624959e+00],
       [ 8.09173555e-02,  1.99644327e-01,  1.20973370e-02, ...,
         1.63782247e-01, -8.98571409e-02, -5.93406741e-01],
       [ 3.77175306e-01, -1.24115418e-03,  3.58266973e-01, ...,
        -4.94957483e-01, -2.39003257e-01, -1.21306047e+00]])

In [9]:
target

array(['A', 'A', 'A', ..., 'A', 'F', 'H'], dtype=object)

In [10]:
#Binarización de la clase para el MLP
y = LabelBinarizer().fit(np.unique(target)).transform(target)

In [11]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### Hold-Out estratificado

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3,
                                                   stratify=target)

In [13]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((13911, 10), (6956, 10), (13911, 12), (6956, 12))

In [14]:
y_pred = np.zeros(y_test.shape, dtype=float)

In [15]:
#Para cada clase
for i in range(y_test.shape[1]):
    #Entrenamiento del conjunto de datos para la clase i
    regr = LinearRegression().fit(x_train, y_train[:,i])
    y_pred[:,i] = regr.predict(x_test)

In [16]:
tasa_ho = accuracy_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))
print("Tasa de aciertos = ", tasa_ho)
print("\nMatriz de Confusión:\n", confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1)))

Tasa de aciertos =  0.48131109833237495

Matriz de Confusión:
 [[2788    0    0    0    3   35    0    0   31    0    0    0]
 [   0    0    0    0    0    0    0    0    3    0    0    0]
 [  55    0    0    0    1    9    0    0    4    0    0    0]
 [ 222    0    0    0    4    1    0    0    8    0    0    0]
 [ 674    0    0    0   11   28    0    0   17    0    0    0]
 [1287    0    0    0    0   12    0    0    9    0    0    0]
 [ 284    0    0    0    0    7    0    0    7    0    0    0]
 [ 274    0    0    0    4   39    0    0   29    0    0    0]
 [  52    0    0    0    3    5    0    0  489    0    5    0]
 [  27    0    0    0    3    0    0    0    0    0    0    0]
 [ 203    0    0    0   13    0    0    0   84    0   48    0]
 [  43    0    0    0    2    0    0    0  130    0    3    0]]


### 3 - Validacion cruzada estratificada

In [17]:
CAPAS=10
acierto=0

In [18]:
skf = StratifiedKFold(n_splits=CAPAS, random_state=0)

In [19]:
#Particiones para el cross-validation estratificado
for train_index, test_index in skf.split(x,target):
    y_pred = np.zeros(y[test_index].shape, dtype=float)
    #Para cada clase
    for i in range(y.shape[1]):
    #Entrenamiento del conjunto de datos para la clase i
        regr = LinearRegression().fit(x[train_index], y[train_index,i])
        y_pred[:,i] = regr.predict(x[test_index])
    acierto += accuracy_score(np.argmax(y[test_index], axis=1), np.argmax(y_pred, axis=1))/CAPAS

In [20]:
print("Tasa de aciertos CV: ", acierto)
print("Tasa de aciertos HO: ", tasa_ho)

Tasa de aciertos CV:  0.4814759959086355
Tasa de aciertos HO:  0.48131109833237495


### 4 - Regresion logística

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
#No es necesario binarizar la clase
y = target

#### Hold-Out estratificado

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3,
                                                   stratify=target)

In [24]:
clf = LogisticRegression(n_jobs=-1, solver='lbfgs', multi_class='auto')
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
y_pred = clf.predict(x_test)

In [26]:
tasa_ho = clf.score(x_test, y_test)
print("Tasa de aciertos = ", tasa_ho)
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Tasa de aciertos =  0.558223116733755

Matriz de Confusión:
 [[2716    0    2    1   32   77    0    9   14    0    5    1]
 [   0    3    0    0    0    0    0    0    0    0    0    0]
 [  45    0    0    0   10    7    0    5    2    0    0    0]
 [ 188    0    0    0   20   10    0   12    2    0    2    1]
 [ 458    0    0    0  160   47    0   13    9    0   40    3]
 [1144    0    1    0   14  127    0    9   11    0    0    2]
 [ 260    0    0    0   10   16    0   10    0    0    2    0]
 [ 197    0    0    0   51   37    0   53    8    0    0    0]
 [  22    0    0    0    2   12    0   13  474    0   13   18]
 [  23    0    0    0    5    0    0    0    0    0    1    1]
 [  33    0    0    0   19    0    0    2   15    4  240   35]
 [  17    0    0    0    1    1    0    1   29    0   19  110]]


#### Validacion cruzada estratificada

In [27]:
CAPAS=10
acierto=0

In [28]:
skf = StratifiedKFold(n_splits=CAPAS, random_state=0)

In [29]:
for train_index, test_index in skf.split(x,y):
    
    clf = LogisticRegression(n_jobs=-1, solver='lbfgs', multi_class='auto')
    clf.fit(x[train_index], y[train_index])
    
    acierto += clf.score(x[test_index], y[test_index])/CAPAS


In [30]:
print("Tasa de aciertos CV: ", acierto)
print("Tasa de aciertos HO: ", tasa_ho)


Tasa de aciertos CV:  0.5614617698815842
Tasa de aciertos HO:  0.558223116733755
