# PRACTICA 1 - ANDRÉS CABERO

## Ganancia - Play Tennis

In [1]:
import pandas as pd
import numpy as np

In [2]:
tennis = pd.read_csv("riesgo.csv")

In [3]:
tennis

Historia Deuda     Avales   Ingresos    Riesgo
0          mala  alta         no     0 a 2M      alto
1   desconocida  alta         no     2 a 5M      alto
2   desconocida  baja         no     2 a 5M  moderado
3   desconocida  baja         no     0 a 2M      alto
4   desconocida  baja         no  más de 5M      bajo
5   desconocida  baja  adecuados  más de 5M      bajo
6          mala  baja         no     0 a 2M      alto
7          mala  baja  adecuados  más de 5M  moderado
8         buena  baja         no  más de 5M      bajo
9         buena  alta  adecuados  más de 5M      bajo
10        buena  alta         no     0 a 2M      alto
11        buena  alta         no     2 a 5M  moderado
12        buena  alta         no  más de 5M      bajo
13         mala  alta         no     2 a 5M      alto

In [4]:
data = np.asarray(tennis)
data

array([['mala', 'alta', 'no', '0 a 2M', 'alto'],
       ['desconocida', 'alta', 'no', '2 a 5M', 'alto'],
       ['desconocida', 'baja', 'no', '2 a 5M', 'moderado'],
       ['desconocida', 'baja', 'no', '0 a 2M', 'alto'],
       ['desconocida', 'baja', 'no', 'más de 5M', 'bajo'],
       ['desconocida', 'baja', 'adecuados', 'más de 5M', 'bajo'],
       ['mala', 'baja', 'no', '0 a 2M', 'alto'],
       ['mala', 'baja', 'adecuados', 'más de 5M', 'moderado'],
       ['buena', 'baja', 'no', 'más de 5M', 'bajo'],
       ['buena', 'alta', 'adecuados', 'más de 5M', 'bajo'],
       ['buena', 'alta', 'no', '0 a 2M', 'alto'],
       ['buena', 'alta', 'no', '2 a 5M', 'moderado'],
       ['buena', 'alta', 'no', 'más de 5M', 'bajo'],
       ['mala', 'alta', 'no', '2 a 5M', 'alto']], dtype=object)

In [5]:
def entropy(data, att):

    #Encontramos los elementos únicos del atributo y calculamos sus probabilidades
    atts = np.unique(data[:,att], return_counts=True)
    probs = atts[1]/data.shape[0]

    #Calculamos la entropía con el siguiente sumatorio
    h = 0
    for p in probs:
        
        h += p*np.log2(1/p)
    
    return h

In [6]:
def gain(data):

    #Calculamos la entropía de la clase (PRE: La clase es la última columna)
    hs = entropy(data, -1)
        
    
    gain = []
    for col in range(data.shape[1]-1):
    
    #Para cada atributo encontramos las posiciones de cada valor diferente
        column = data[:,col]
        atts = np.unique(column)
        idx = [np.where(column==a) for a in atts]

    #Calculamos la ganancia del atributo calculando la entropía de la clase para cada valor distinto del atributo
        sum = 0
        for i in idx:
            sum += entropy(data[i], -1)*(len(i[0])/data.shape[0])
        gain.append(hs-sum)
            
    return gain

In [7]:
gains = gain(data)

for i in range(len(gains)):
    print("Ganancia de", tennis.columns[i], ": %.4f" % gains[i])

1.2649647103247632
1.467720100474499
1.3245694857630952
0.5642953235635804
Ganancia de Historia : 0.2657
Ganancia de Deuda : 0.0629
Ganancia de Avales : 0.2060
Ganancia de Ingresos : 0.9663


In [1]:
import numpy as np

In [2]:
A = np.asarray([[2,7,6],[-3,4,2],[1,-1,0]])
B = np.asarray([[2/33,2/11,-10/33],[-2/33,-2/11,-2/3],[-1/33,-3/11,29/33]])

In [6]:
A

array([[ 2,  7,  6],
       [-3,  4,  2],
       [ 1, -1,  0]])

In [12]:
inverse = np.linalg.inv(A)

In [16]:
inverse

array([[ 0.16666667, -0.5       , -0.83333333],
       [ 0.16666667, -0.5       , -1.83333333],
       [-0.08333333,  0.75      ,  2.41666667]])

In [17]:
np.matmul(A,B)

array([[-4.84848485e-01, -2.54545455e+00,  2.22044605e-16],
       [-4.84848485e-01, -1.81818182e+00,  2.22044605e-16],
       [ 1.21212121e-01,  3.63636364e-01,  3.63636364e-01]])

In [15]:
1+2.77555756e-17

1.0

In [18]:
np.linalg.det(A)

11.999999999999995